name: uFormat

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ufmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # setup python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # install poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      # run ufmt
      - uses: omnilib/ufmt@action-v1
        with:
          path: .
          requirements: requirements.txt
          python-version: "3.x"
